### ISSUE TITLE
Thermal Blocks

### ISSUE THREAD

**Issue by joedevivo** [radensb/TAZ6-Archim2-Conversion#2]
Thanks for this guide. I just upgraded my TAZ 6 to the Archim2, and after some trial and error, I have everthing working, but there's still something unresolved.

The thermal blocks on my Archim2 are set up as Heat0, Heat1, Heat2, Fan0, HeatedBed. The RAMBo was set up for Heat0, Fan0, Heat1, Fan1, Heated Bed, which is how the photos in your guide look.

Since I only have one extruder, I just didn't hook up Heat1, mostly because I have no idea where to put Fan1. Except that there is a Fan1, but that's the exhaust fan. 

How do you have it wired?

**Comment by radensb** [comment]
It's a bit confusing as the naming does not match 1:1. Also, Lulzbot does not use both RAMBo Fan0 and Fan1 simultaneously and the active fan changes based on what toolhead is installed (single vs dual).

### **Archim2 naming used below unless otherwise specified.**
Below is the schematic for the Archim2. All the thermal block circuits are the same. The only difference is that Fan0 and Fan1 circuits use a different FET to switch power. The Lulzbot configuration is just using the Heat1 circuit to run a fan. So, the mapping looks like:

**Archim2   ->   RAMBo**

- Heat0    ->   Heat0
- Heat1    ->   Fan0 (part cooling fans on single extruder)
- Heat2    ->   Heat1
- Fan0      ->   Fan1 (part cooling fans on dual extruder)
- Bed       ->   Bed

Again, with respect to the Archim2 naming, my configuration utilizes Fan1 (the separate, 2-pin connector below and to the left of the thermal block) to run the enclosure exhaust fan, and Fan0 to run the part cooling fans on the toolhead **(I have a dual extruder toolhead)**. The single extruder toolhead uses Heat1 for the part cooling fans.

- With the Lulzbot single extruder, Archim2's Heat1 (RAMBo Fan0) controls the part cooling fans (and RAMBo Fan1 is unused).
- With the Lulzbot Dual v3 (what I am currently running), the Archim2's Fan0 (RAMBo Fan1) controls the part cooling fans (and RAMBo Fan0 is unused).


**Additional info::**
With a dual extruder, it get even more fun because the way Lulzbot defined the wiring, the heaters also change between toolheads because the single extruder wiring harness connects to E2 on a dual:

(Archim2 Naming Used)
**Single**
- Heat0 -> E1
- Heat1 -> Part Cooling Fans
- Heat2 -> unused
- Fan0 -> unused
- Bed -> Bed

**Dual**
- Heat0 -> E2
- Heat1 -> unused
- Heat2 -> E1
- Fan0 -> Part Cooling Fans
- Bed -> Bed

They couldn't even keep the extruder numbers zero indexed... Why Lulzbot? ...Why?


**Archim2 Thermal Block Schematic**
![image](https://user-images.githubusercontent.com/35448905/87589758-97aa3900-c69a-11ea-9260-8f1fe47b76ab.png)

**Comment by joedevivo** [comment]
Ha! If I had a nickel for every time I asked "Why Lulzbot?" :D

I think I'm following. Can you point me at how you have your firmware configured?

**Comment by radensb** [comment]
I am running the [Klipper firmware](https://www.klipper3d.org/). It is a very interesting project that I find works exceptionally well. If you already know about it, you can skip the rest. :)

Instead of the printer controller board parsing ascii gcode and generating movement instructions, the gcode is parsed and processed on a much faster machine (Raspberry Pi) with kinematic models applied for very smooth operation. The Pi then sends optimized instructions to the printers controller board (the Archim2 in this case) that simply preforms the movement and reports the temps, etc. Octoprint is the user interface of choice via a plugin.

This may seem like a waste of a 32-bit board as all the brains are moved into the Pi, but the combination of silent drives, native USB, and a ton more internal resources (like RAM) allow the printer to run very fast and smooth. My old RAMBo board could not keep up with Klipper. The 8-bit MCU and USB-Serial converter just didnt have it in her. The near plug-n-play Archim2 solved that. 

Also, Klipper is extremely simple to configure and customize. Everything is defined in a config file and adding peripherals (like servos, BLTouch, lights, fans, heaters, etc) just require defining the new item and what pins it is interfaced on. There is a generic config file on the Klipper Github for the Archim2. I plan to commit my TAZ6 version soon, but the basics to get going are already in the generic one. The down side is it is mainly implemented in Python. I suck at Python. Good'ol Marlin was C++ - which I have been coding in for 20 years... Unfortunately, large parts of Marlin is a dumpster fire.

**Comment by joedevivo** [comment]
I've tried klipper, but when I successfully flash the firmware the Archim2 lets out a whine, which it always does on a firmware flash, but when I turn it off and on, nothing comes on the screen and the whine starts again, and keeps going... forever. That ever happen to you?

**Comment by radensb** [comment]
Cant say I recall a "whine", but the screen will stay blank if your config file was rejected due to misconfiguration (syntax). What creates the whine noise? I dont think there is a speaker on that board... :)

I have included a snippet of my config file that should get you up and running. Use it to compare with your config file. I disabled some advanced features like pressure advance and my BLTouch probe, so there is no probe support. However, it should get the machine moving. Please check for:

- *** VERIFY/UPDATE FOR SINGLE ***
- *** VERIFY FOR SINGLE ***

notes as these may need to be adjusted for a single extruder before trying to home the machine.
[Klipper_TAZ6_BasicCgf.cfg.txt](https://github.com/radensb/TAZ6-Archim2-Conversion/files/4951029/Klipper_TAZ6_BasicCgf.cfg.txt)

**Comment by joedevivo** [comment]
I'll take another crack at this over the weekend. Would you mind sharing your `klipper/.config`?

**Comment by vitormhenrique** [comment]
hello @radensb I'm looking foward to do this upgrade on my taz 6, would you mind sharing tour `.config` file?
Amazing project and documentation!
Thank you very much!
